### ISSUE TITLE
Module 4 setup script '01-environment-setup.ps1' issue?

### ISSUE THREAD

**Issue by DynamicChipmunk** [solliancenet/microsoft-data-engineering-ilt-deploy#10]
I am hoping to get prepped to take dp-203 tests and all, but I feel like there may be a pathing issue in the Module 4 ‘.\01-environment-setup.ps1’ script.  At least, in the last few attempts to run it – although it otherwise seems to ‘succeed’ - I see these unexplained errors consistently.  (I have tried running this in both a fresh Win10 laptop locally (configured as is recommended for the deployment VM referenced in the overall Mod 4 setup docs) and also in an Azure deploy VM, also configured identically to what the docs recommend)

Get-Content : Cannot find path 'C:\labfiles\data-engineering-ilt-deployment\setup\04\artifacts\day-02\lab-05-security\Lab 05 - Exercise 3 - Column Level Security.sql' because it does not exist.

Get-Content : Cannot find path 'C:\labfiles\data-engineering-ilt-deployment\setup\04\artifacts\day-02\lab-05-security\Lab 05 - Exercise 3 - Dynamic Data Masking.sql' because it does not exist.

Get-Content : Cannot find path 'C:\labfiles\data-engineering-ilt-deployment\setup\04\artifacts\day-02\lab-05-security\Lab 05 - Exercise 3 - Row Level Security.sql' because it does not exist.

Get-Content : Cannot find path 'C:\labfiles\data-engineering-ilt-deployment\setup\04\artifacts\day-02\Activity 03 - Data Warehouse Optimization.sql' because it does not exist.

This seems to be ‘expected’, in the sense that those files are not present in the dir they are being called from – although they do seem to exist in a dir ‘workspace-artifacts’ that lives just under the ‘sql’ dir.  

Is it possible that those 4 files are obsolete and have been superseded – so maybe I shouldn’t worry about those errors?  Or, alternatively, should the ‘missing’ files be copied into a dir the script will be able to find/use so we don’t see the errors when running 01-environment-setup.ps1?

**Comment by joelhulen** [comment]
Good catch! Yes, there were recent changes that impacted the paths. Thanks!
