### ISSUE TITLE
Error setup lab module 2

### ISSUE THREAD

**Issue by molenaar** [solliancenet/microsoft-data-engineering-ilt-deploy#5]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"RoleAssignmentUpdateNotPermitted","message":"Tenant ID, application ID, principal ID, and scope are not allowed to be updated."},{"code":"InternalServerError","message":"An unexpected error occured while processing the request. Tracking ID: 'f3f70c08-392f-42b3-831e-b54a0c5a0747'"}]}

Deployment error for module 2.
Synapse analytics gives a conflict.
Role Assignment gives a bad request

**Comment by molenaar** [comment]
Is for the Module 2 lab setup

**Comment by joelhulen** [comment]
I just successfully deployed module 2.

![image](https://user-images.githubusercontent.com/5950304/115238180-652ae200-a0eb-11eb-8e68-f47eb5f236bf.png)

Which Azure region did you deploy this to? I just tested this out with South Central US.

**Comment by molenaar** [comment]
West europe

**Comment by molenaar** [comment]
Setup seems to be fine now!
