### ISSUE TITLE
Creation of Dediciated SQL Pools fail

### ISSUE THREAD

**Issue by molenaar** [solliancenet/microsoft-data-engineering-ilt-deploy#6]
During deployment, dedicated SQL Pools fail to be created often.
After than the .\01-environment-setup.ps1 often fails trying to connect to the SQLPool01

**Comment by joelhulen** [comment]
@molenaar, can you please let me know which module setup this is for? Is it module 4? Can you share any error messages you are receiving?

**Comment by molenaar** [comment]
Module 1, 2,4 and 14.
First I created a dp-203 resource group, but setting up the labs for module 1 and 2 in the same group will not work.
The internal group created by the synapse workspace gives an error, the RG already exists.

So I created 4 RG groups: for module 1,2,4 and 16 and started the deployments again.

Removing synapse workspaces takes a very long time, however. And it seems when you redeploy that the workspace name is reserved for at least 4 hours.

For module 1 it created the full set with a spark pool but without the sqlpool01. Also module 2, 4 and 16 give either a workspace error, an event hub error or a Sqlpool01 error. Manually creating the SQLPool1 and redeploy the arm deployment (from the portal) wasn't a success.

Now I removed all RGs and I will try it again. Then everything should be really deleted.

Wouldn't it be a good idea to suggest the names of the resource groups? And mention that if you already deployed the environment.for.module 4, its not needed to deploy it again in for example module 5.

A lab hosted environment would make things a lot easier, however not available right now. So I need to deploy it in my subscription for preparation. I have dp-203 classes in May.

**Comment by molenaar** [comment]
I also used the VM created in module 4 for later deployments during the day.

**Comment by joelhulen** [comment]
@molenaar,

You can reuse a lot of the same environments for the labs. Please review this section in the main README of the repo: https://github.com/solliancenet/microsoft-data-engineering-ilt-deploy#modules-that-can-share-the-same-synapse-workspace

**Comment by molenaar** [comment]
Setups seem to be fine now!

**Comment by joelhulen** [comment]
I'm glad to hear it!
