### ISSUE TITLE
Mod 1 Lab 2 Unique Suffix N/A for Provisioned Environment?

### ISSUE THREAD

**Issue by Kaijisse** [solliancenet/microsoft-data-engineering-ilt-deploy#9]
Add a new cell to your notebook with the following code (remember to replace <unique_suffix> with the value you specified during the Synapse Analytics workspace deployment):

There is no unique suffix provided when someone uses a pre-configured environment, in which they shouldn't have to deploy the Synapse Analytics workspace. 

When stating: Replace the value below with the name of your primary ADLS Gen2 account for your Synapse workspace, which of these two we mean:
![image](https://user-images.githubusercontent.com/38757647/116551550-5668da00-a8f8-11eb-9cda-893ca0401585.png)

It might cause some confusion.

**Comment by joelhulen** [comment]
Both can be used. The resource is `asadatalakeNNNNN`, as stated in the instructions. In the first option, it's in the parentheses after "Primary - ". In the second option, it's directly in the name of the resource.
